statusbar: false
menubar: false
toolbar: bold italic | bullist numlist | link | table
plugins:
  - table
  - autoresize
  - link
target_list: false 
autoresize_min_height: 130
extended_valid_elements : "iframe[tooltip] , a[href|target=_blank]"